"""Deterministic offline analytical backtesting contracts."""

from app.services.backtesting.exceptions import (
    BacktestExecutionConfigurationMismatchError,
    BacktestExecutionDatasetMismatchError,
    BacktestExecutionError,
    BacktestExecutionStructuralError,
    BacktestValidationError,
    HistoricalDatasetDuplicateError,
    HistoricalDatasetDigestMismatchError,
    HistoricalDatasetImportError,
    HistoricalDatasetReadError,
    HistoricalDatasetSyntaxError,
    HistoricalDatasetValidationError,
    InvalidBacktestExecutionRequestError,
    UnsupportedHistoricalDatasetSchemaError,
)
from app.services.backtesting.execution import BacktestExecutionService
from app.services.backtesting.execution_models import (
    BacktestExecutionConfiguration,
    BacktestExecutionMetadata,
    BacktestExecutionRequest,
    BacktestExecutionResult,
)
from app.services.backtesting.evaluation_models import (
    BacktestStudyEvaluation,
    CriterionObservation,
    CriterionObservationStatus,
)
from app.services.backtesting.eligibility_models import (
    EligibilityRequirementResult,
    ProductionEligibilityAssessment,
    PromotionRequirementKind,
)
from app.services.backtesting.import_models import (
    HISTORICAL_DATASET_SCHEMA_VERSION,
    HistoricalDatasetCustody,
    HistoricalDatasetDigest,
    HistoricalDatasetImportResult,
    HistoricalDatasetManifest,
    HistoricalDatasetProvenance,
)
from app.services.backtesting.importer import (
    HistoricalDatasetCanonicalizer,
    HistoricalDatasetImporter,
)
from app.services.backtesting.models import (
    BacktestExclusion,
    BacktestExclusionReason,
    ComparisonOperator,
    DistributionSummary,
    MedianVsrThresholdCandidate,
    MedianVsrThresholdSet,
    QualificationFailureCount,
    QualificationCoverageSummary,
    SubscriberBandBacktestResult,
    SubscriberBandDefinition,
    SubscriberBandSet,
    SubscriberRelativeBacktestDataset,
    SubscriberRelativeBacktestObservation,
    ThresholdBacktestReport,
    ThresholdEvaluationResult,
)
from app.services.backtesting.promotion_models import (
    ApprovedProductPolicyRequirement,
    ApprovedStudyRequirement,
    MethodologyVersionRequirement,
    ProductionPromotionPolicy,
    PromotionRequirement,
    ReleaseGovernanceReviewsRequirement,
)
from app.services.backtesting.methodology_models import (
    ResearchRecommendation,
    ThresholdEvaluationCriterion,
    ThresholdEvaluationMethodology,
    ThresholdEvaluationMetric,
)
from app.services.backtesting.service import (
    MedianStandardVideoVsrThresholdBacktester,
)
from app.services.backtesting.study_models import (
    BacktestStudyArtifact,
    BacktestStudyDecision,
    BacktestStudyDefinition,
    BacktestStudyReview,
    BacktestStudyStatus,
)
from app.services.backtesting.validation import BacktestDatasetValidator

__all__ = [
    "BacktestExecutionConfiguration",
    "BacktestExecutionConfigurationMismatchError",
    "BacktestExecutionDatasetMismatchError",
    "BacktestExecutionError",
    "BacktestExecutionMetadata",
    "BacktestExecutionRequest",
    "BacktestExecutionResult",
    "BacktestExecutionService",
    "BacktestExecutionStructuralError",
    "BacktestStudyArtifact",
    "BacktestStudyDecision",
    "BacktestStudyDefinition",
    "BacktestStudyEvaluation",
    "BacktestStudyReview",
    "BacktestStudyStatus",
    "BacktestDatasetValidator",
    "BacktestExclusion",
    "BacktestExclusionReason",
    "BacktestValidationError",
    "ApprovedStudyRequirement",
    "ApprovedProductPolicyRequirement",
    "ComparisonOperator",
    "CriterionObservation",
    "CriterionObservationStatus",
    "DistributionSummary",
    "EligibilityRequirementResult",
    "HISTORICAL_DATASET_SCHEMA_VERSION",
    "HistoricalDatasetDuplicateError",
    "HistoricalDatasetDigestMismatchError",
    "HistoricalDatasetCanonicalizer",
    "HistoricalDatasetCustody",
    "HistoricalDatasetDigest",
    "HistoricalDatasetImportError",
    "HistoricalDatasetImporter",
    "HistoricalDatasetImportResult",
    "HistoricalDatasetManifest",
    "HistoricalDatasetProvenance",
    "HistoricalDatasetReadError",
    "HistoricalDatasetSyntaxError",
    "HistoricalDatasetValidationError",
    "InvalidBacktestExecutionRequestError",
    "MedianStandardVideoVsrThresholdBacktester",
    "MedianVsrThresholdCandidate",
    "MedianVsrThresholdSet",
    "MethodologyVersionRequirement",
    "ProductionPromotionPolicy",
    "ProductionEligibilityAssessment",
    "PromotionRequirement",
    "PromotionRequirementKind",
    "QualificationFailureCount",
    "QualificationCoverageSummary",
    "ResearchRecommendation",
    "ReleaseGovernanceReviewsRequirement",
    "SubscriberBandBacktestResult",
    "SubscriberBandDefinition",
    "SubscriberBandSet",
    "SubscriberRelativeBacktestDataset",
    "SubscriberRelativeBacktestObservation",
    "ThresholdBacktestReport",
    "ThresholdEvaluationCriterion",
    "ThresholdEvaluationMethodology",
    "ThresholdEvaluationMetric",
    "ThresholdEvaluationResult",
    "UnsupportedHistoricalDatasetSchemaError",
]
